language: node_js
node_js:
  - 14
branches:
  only:
    - 'master'
cache:
  directories:
    - node_modules
deploy:
  provider: npm
  email: '914440302@qq.com'
  api_key: '$NPM_TOKEN'
  on:
    tags: true
  skip_cleanup: true
